### ISSUE TITLE
ResizeCanvas not working

### ISSUE THREAD

**Issue by ademc** [serenity-is/sleekgrid#10]
In the older versions of Serenity, we used the resizeCanvas() method to ensure that the grid was resized appropriately when the screen was resized or the data changed, so that it would fit the container's available space. However, now this method, as well as other methods like layout and render, have no effect. How can I ensure that the grid's dimensions are automatically updated to fit the container's occupied area?

**Comment by VictorTomaili** [comment]
resizeCanvas affects the sleekgrid. In serenity, the grid is a wrapper of the sleekgrid. So, you need to ensure the container element (serenity grid) fits the parent. For this reason, you can use flex layout to ensure serenity grid always fits to the container. And please use serenity discussions to ask questions. These issues are related sleekgrid bugs, issues etc. Not for questions. We cannot follow all repositories for questions.

**Comment by ademc** [comment]
Please do not simply categorize and ignore the problems that people are facing. Serenity, its components, and its community, as well as its main creators, are the result of serious effort. We also put a lot of effort into our work. After many trials and errors, we turn to this place when we find ourselves at an impasse.

First of all, the environment in which I use the library is already part of the current Serenity project. Therefore, the areas are already using the Flex layout. UNfortunatelly, it is not working as you said

I'm sharing the solution I found in case someone else has a similar problem and comes here. At least, I hope you'll show the courtesy of not deleting it.

I set a fixed height for the field container.
For the grid element, I set the height to 100% and overflow to auto.
```
this.form.GridField.element.parent().style(c => {
    c.height = "750px";
});
this.form.GridField.element.style(c => {
    c.border = "none";
    c.height = "100%";
    c.overflow = "auto";
});
```
However, since this was not a solution, I needed to remove the manually assigned height from the viewport. 
After doing 
`this.form.Result.element.findFirst(".slick-viewport").style(c => { c.height = '100%' }), `

I was able to get the expected behavior.

**Comment by VictorTomaili** [comment]
Primarily, I attempted to replicate your issue on the StartSharp project but was unable to do so. It appears that this matter is related to Serenity rather than SleekGrid. Therefore, you may have directed your query to the incorrect place. Nevertheless, I endeavored to address your concern, as it pertains to grid editors rather than grid pages, as demonstrated below:

![image](https://github.com/serenity-is/sleekgrid/assets/2023440/7d0ffe10-08fc-46fe-9034-e8e85d4c50c5)

Allow me to explain step-by-step:

- The forms utilize a flex layout to keep fields positioned at the top as much as possible.
- The `.categories` class uses `display:block` by default and collapses the entire view with `flex: 1 1 auto`.
- The `.category` class, which is the container for multiple fields, should maintain the fields at the top using the flex layout:
```css
.category {
    display: flex;
    flex-wrap: wrap;
    min-width: 0;
    flex-direction: row;
}
```
- Each field is considered a row and should minimize its area with the following CSS:

```css
.field {
    display: flex;
    flex-wrap: nowrap;
    align-items: flex-start;
    flex: 0 1 100%;
    min-width: 0;
    padding-right: 0.75rem;
    padding-left: 0.75rem;
    padding-top: 0.5rem;
    padding-bottom: 0.5rem;
}
```

- The grid editor is also a field and should use minimal area to allow for the addition of other fields below:

![image](https://github.com/serenity-is/sleekgrid/assets/2023440/66134acf-a087-446d-ba7b-1e17b6785487)

- The category uses less area than categories, ensuring that the fields are correctly positioned.

I understand that your question involves making the grid editor fill the bottom area. The `.category` element expands when the inner editor requires more space. For your specific case, you need to set the height for the `.s-OrderDetailsEditor` in your CSS file:

```css
.s-OrderDetailsEditor {
    height: 500px;
}
```

Setting the height `100%` does not work due to the container not filling the available space, if you need to fill the below empty area, you need to use JavaScript to calculate the remaining empty area and set the editor height accordingly.

As your question was directed to the incorrect place, I closed this issue. However, I wanted to take the opportunity to guide you toward a resolution for your problem in my previous answer and now.

Thank you for your understanding.
